package com.garethahealy.githubstats.commands.users;

import com.garethahealy.githubstats.factories.LdapConnectionFactory;
import com.garethahealy.githubstats.processors.users.jobs.CreateWhoAreYouIssueProcessor;
import freemarker.template.TemplateException;
import jakarta.inject.Inject;
import org.apache.directory.api.ldap.model.exception.LdapException;
import org.kohsuke.github.GHPermissionType;
import picocli.CommandLine;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.ExecutionException;

@CommandLine.Command(name = "create-who-are-you-issues", mixinStandardHelpOptions = true, description = "Creates a single issue in the org config for users that are not known")
public class CreateWhoAreYouIssueCommand implements Runnable {

    @CommandLine.Option(names = {"-org", "--organization"}, description = "GitHub organization", required = true)
    String organization;

    @CommandLine.Option(names = {"-repo", "--issue-repo"}, description = "Repo where the issues should be created, i.e.: 'org'")
    String orgRepo;

    @CommandLine.Option(names = {"-i", "--ldap-members-csv"}, description = "CSV of known members, generated by 'collect-members-from-ldap'", defaultValue = "ldap-members.csv")
    String ldapMembersCsv;

    @CommandLine.Option(names = {"-s", "--supplementary-csv"}, description = "CSV of known members collected manually or via the google form", defaultValue = "supplementary.csv")
    String supplementaryCsv;

    @CommandLine.Option(names = {"-p", "--permission"}, description = "Permission to search against; ADMIN, WRITE, READ", required = true)
    String permission;

    @CommandLine.Option(names = {"-l", "--team-limit"}, description = "Number of GitHub teams to check", defaultValue = "0")
    int limit;

    @CommandLine.Option(names = {"-g", "--guess"}, description = "Attempt to guess users we cant look up via InfoSec LDAP", defaultValue = "false")
    boolean shouldGuess;

    @CommandLine.Option(names = {"-dry", "--dry-run"}, description = "Dry-run aka don't actually create the GitHub issues", required = true)
    boolean dryRun;

    @CommandLine.Option(names = {"-vpn", "--fail-if-no-vpn"}, description = "Throw an exception if can't connect to LDAP", defaultValue = "true")
    boolean failNoVpn;

    @Inject
    CreateWhoAreYouIssueProcessor createWhoAreYouIssueProcessor;

    @Inject
    LdapConnectionFactory ldapConnectionFactory;

    @Override
    public void run() {
        try {
            if (!ldapConnectionFactory.canConnect()) {
                if (failNoVpn) {
                    throw new IOException("Unable to connect to LDAP. Are you on the VPN?");
                }
            }

            Path ldapMembersPath = Path.of(ldapMembersCsv);
            if (!Files.exists(ldapMembersPath)) {
                throw new FileNotFoundException("--ldap-members-csv=" + ldapMembersCsv + " not found.");
            }

            Path supplementaryPath = Path.of(supplementaryCsv);
            if (!Files.exists(supplementaryPath)) {
                throw new FileNotFoundException("--supplementary-csv=" + supplementaryCsv + " not found.");
            }

            if (!dryRun && (orgRepo == null || orgRepo.isEmpty())) {
                throw new IllegalArgumentException("--dry-run=" + dryRun + " but --issue-repo=" + orgRepo + " - 'issue-repo' cant be empty if 'dry-run' is false");
            }

            createWhoAreYouIssueProcessor.run(organization, orgRepo, ldapMembersPath.toFile(), supplementaryPath.toFile(), convert(permission), limit, dryRun, shouldGuess);
        } catch (IOException | TemplateException | ExecutionException | InterruptedException | LdapException e) {
            throw new RuntimeException(e);
        }
    }

    private GHPermissionType convert(String permissions) {
        GHPermissionType answer;
        if (permissions.equalsIgnoreCase("ADMIN")) {
            answer = GHPermissionType.ADMIN;
        } else if (permissions.equalsIgnoreCase("WRITE")) {
            answer = GHPermissionType.WRITE;
        } else if (permissions.equalsIgnoreCase("READ")) {
            answer = GHPermissionType.READ;
        } else {
            throw new IllegalArgumentException("--permission=" + permissions + " is invalid.");
        }

        return answer;
    }
}
